version: '2.4'
services:
  quickstart-host:
    platform: linux/x86_64
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    ports:
      - "1280:1280"
      - "3022:3022"
      - "6262:6262"
    environment:
      - "EXTERNAL_DNS=${EXTERNAL_DNS}"
      - "ZITI_EDGE_ROUTER_RAWNAME=${ZITI_EDGE_ROUTER_HOSTNAME}"
      - "ZITI_EDGE_CONTROLLER_HOSTNAME=${ZITI_EDGE_CONTROLLER_HOSTNAME}"
      - "ZITI_EDGE_ROUTER_HOSTNAME=${ZITI_EDGE_ROUTER_HOSTNAME}"
    networks:
      quickstart-test:
        aliases:
          - ziti-edge-controller
    entrypoint:
      - "/tmp/local-quickstart-setup.sh"

  web-test:
    image: crccheck/hello-world
    ports:
      - "80:8000"
    networks:
      quickstart-test:
        aliases:
          - web-test

networks:
  quickstart-test:
    driver: bridge